### ISSUE TITLE
Create CSV file from API Call

### ISSUE THREAD

**Issue by jcornelius** [ninelabs/atl-tech-meetups#1]
We need a script that will reliably pull information from the Meetup API and put it into a CSV file.

The [Find Groups](https://www.meetup.com/meetup_api/docs/find/groups/) method seems to be the best way to get the information we need. You can put the fields in any order, so long as they are labeled with a header row.

### Parameters for the Request

```
'zip'                  => '30363',
'radius'               => '50',
'category'             => '34',
'order'                => 'members',
'fields'               => 'key_photo,plain_text_description',
'text_format'          => 'plain',
'fallback_suggestions' => 'false'
```

We prefer this be written in Ruby or PHP. Here is a list of [Meetup API Clients](https://github.com/meetup/api/blob/master/clients.md#meetup-api-client-libraries) that may help.

**Comment by wshatch** [comment]
What parameters for find were used to get the meetups on the README?

**Comment by jcornelius** [comment]
@wshatch The ones listed above.

**Comment by wshatch** [comment]
What columns should be in the CSV?

**Comment by jcornelius** [comment]
- Group Name
- Meetup URL
- key_photo->photo_link
- plain_text_description
- members

**Comment by jcornelius** [comment]
Thanks, @wshatch!
