### ISSUE TITLE
WP Job Manager post to Slack Notification

### ISSUE THREAD

**Issue by jcornelius** [ninelabs/atl-tech-meetups#5]
# Summary
As a user of tech404, I would like to have a notification of jobs posted to the job board appear in the appropriate channel in the tech404 Slack team.

#### Technologies used
- [WP Job Manager](https://github.com/Automattic/WP-Job-Manager) 
- [Slack API messages](https://api.slack.com/docs/messages)

## Overview
We would like a notification posted to the appropriate channel when jobs are _successfully approved_ in WP Job Manager. Notifications should only be posted to Slack with a job is *approved*, not when submitted.

The Message should include:
- Job type (in the message title)
- The title of the job post, which links to the post on tech404. 
- Job description, truncated to 200 characters 
- Company name
- Company logo
- Job location

Here's an example of the message payload that needs to be created for Slack.

### Slack JSON Payload
```
{
    "attachments": [
        {
            "pretext": "New {{job_type}} Job posting!",
            "color": "#36a64f",
            "title": "{{job_title}}",
            "title_link": "https://tech404.io/job/{{job_posting_slug}}",
            "text": "{{job_description:truncate:200}}",
            "thumb_url": "{{job_company_logo}}",
            "fields": [
                  {
                        "title": "Company",
                        "value": "{{job_company_name}}",
                        "short": true
                  },
                  {
                        "title": "Location",
                        "value": "{{job_location}}",
                        "short": true
                  }
            ]
        }
    ]
}
```
### Payload Example
```
{
   "attachments": [
      {
            "pretext": "New Full-time Job posting!",
            "color": "#36a64f",
            "title": "Sr. User Experience Designer",
            "title_link": "https://tech404.io/job/slug-to-job-posting",
            "text": "Terminus is a fast growing technology company in Atlanta, challenging the status quo of B2B marketing. We've built an industry-leading Account-Based Marketing (ABM) platform that enables our customers to be more targeted in reaching their ideal customers, driving powerful business outcomes including an increase in revenue and acceleration of pipeline velocity.",
            "thumb_url": "https://tech404.io/wp-content/uploads/job-manager-uploads/company_logo/2018/02/terminus.png",
            "fields": [
                  {
                        "title": "Company",
                        "value": "Awesome Startup",
                        "short": true
                  },
                  {
                        "title": "Location",
                        "value": "Atlanta, GA",
                        "short": true
                  }
            ]
        }
    ]
}
```

The resulting post in Slack should look like this:
![screenshot 2018-02-11 12 09 42](https://user-images.githubusercontent.com/366136/36075995-82e01fe2-0f24-11e8-82da-144afc577572.png)

Also: see this [API Message Builder](https://api.slack.com/api_docs_message_builder.php?msg=%7B%22attachments%22%3A%5B%7B%22pretext%22%3A%22New%20Full-time%20Job%20posting!%22%2C%22color%22%3A%22%2336a64f%22%2C%22title%22%3A%22Sr.%20User%20Experience%20Designer%22%2C%22title_link%22%3A%22https%3A%2F%2Ftech404.io%2Fjob%2Fslug-to-job-posting%22%2C%22text%22%3A%22Terminus%20is%20a%20fast%20growing%20technology%20company%20in%20Atlanta%2C%20challenging%20the%20status%20quo%20of%20B2B%20marketing.%20We%27ve%20built%20an%20industry-leading%20Account-Based%20Marketing%20(ABM)%20platform%20that%20enables%20our%20customers%20to%20be%20more%20targeted%20in%20reaching%20their%20ideal%20customers%2C%20driving%20powerful%20business%20outcomes%20including%20an%20increase%20in%20revenue%20and%20acceleration%20of%20pipeline%20velocity.%22%2C%22thumb_url%22%3A%22https%3A%2F%2Ftech404.io%2Fwp-content%2Fuploads%2Fjob-manager-uploads%2Fcompany_logo%2F2018%2F02%2Fterminus.png%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Company%22%2C%22value%22%3A%22Awesome%20Startup%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Location%22%2C%22value%22%3A%22Atlanta%2C%20GA%22%2C%22short%22%3Atrue%7D%5D%7D%5D%7D)

### Job-type to Slack channel mapping
There are 5 job types supported by the WP Job Manager plugin on the tech404 website.
1. Full-time
2. Part-time
3. Internship
4. Temporary
5. Freelance

There are currently three channels in the tech404 Slack team for job postings:
1. #jobs
2. #gigs
3. #freelance

Job types should be mapped to channels as follows:

1. Full-time > #jobs
2. Part-time > #jobs
3. Internship > #gigs
4. Temporary > #gigs
5. Freelance > #freelance

**Comment by nicdev** [comment]
@jcornelius I'll be glad to take on this. Please assign it when you have a minute.

**Comment by nicdev** [comment]
@jcornelius you can download the plugin [here](https://github.com/nicdev/job-approval-notification/releases/tag/0.1)
It piggy-backs off of the Slack notifications plugin you mentioned. That plugin is somewhat limited, and I may contribute some improvements in the future, but for the time being this should work. I had to pass most of the information as Slack "attachments". 
![sample](https://cl.ly/3b0A0O1V132g/Screen%20Shot%202018-02-15%20at%208.12.27%20PM.png)

**Comment by jcornelius** [comment]
Thanks, @nicdev! Slack Attachments shouldn't be an issue. The Payload Example above uses attachments, too.

**Comment by nicdev** [comment]
@jcornelius yup, the attachments work fine, but some of the other options get stripped out by the plugin. I think my next update will be to NOT piggy back off of the other plugin for notifications.
